### PR TITLE
Fix logger and reset mode

### PR DESCRIPTION
**Pull request by jMaddrell**
example log for connection failure
```
❯ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/rs-flasher`

KNOMI Firmware Installer by DiverOfDark
==================================================================

Firmware info: https://github.com/DiverOfDark/KNOMI
Branch: feature/bump-espflash-rust (07ef4fb8bd6687df893607ab24b34106a3043ebd)
Source Timestamp: 2024-04-02 21:01:18
Binary Timestamp: 2024-04-03 08:26:08

==================================================================

This tool will flash alternative KNOMI firmware to your device.
Please put your KNOMI into flash mode (press button and connect cable).


✔ Do you want to continue? · yes
[2024-04-03T16:11:18Z ERROR rs_flasher] Firmware flashing error!
[2024-04-03T16:11:18Z ERROR rs_flasher] Error while connecting to device
[2024-04-03T16:11:18Z ERROR rs_flasher] Press Enter to exit
```

Log for a successful flash:
```

❯ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/rs-flasher`

KNOMI Firmware Installer by DiverOfDark
==================================================================

Firmware info: https://github.com/DiverOfDark/KNOMI
Branch: feature/bump-espflash-rust (07ef4fb8bd6687df893607ab24b34106a3043ebd)
Source Timestamp: 2024-04-02 21:01:18
Binary Timestamp: 2024-04-03 08:26:08

==================================================================

This tool will flash alternative KNOMI firmware to your device.
Please put your KNOMI into flash mode (press button and connect cable).


✔ Do you want to continue? · yes
[00:03:42] [========================================]    1996/1996    0x1000
```

### CODE REVIEW

**Comment by jMaddrell** [comment]
Would also be good to produce a native macOS arm build, seems as simple as adding this to the actions

```
rustup target add aarch64-apple-darwin
cargo build --target aarch64-apple-darwin
```

**Review by DiverOfDark — APPROVED** [review]

**Comment by DiverOfDark** [comment]
> Would also be good to produce a native macOS arm build, seems as simple as adding this to the actions

Added to github actions and built patch release - https://github.com/DiverOfDark/KNOMI/releases/tag/v2.1.3
I don't have any mac device - so can't test if it works at all :).

**Comment by jMaddrell** [comment]
I’ll give it a test tomorrow evening

**Comment by jMaddrell** [comment]
Just tested the macOS arm build works fine 😄

**Pull request merged**
